# Adicione este bloco no TOPO do arquivo
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build da imagem
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oda-siconfi', '.']

  # 2. Push da imagem
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/oda-siconfi']

  # 3. Deploy do Job (Aqui você já declarou as variáveis, está perfeito!)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'oda-siconfi-finbra'
      - '--image'
      - 'gcr.io/$PROJECT_ID/oda-siconfi'
      - '--region'
      - 'southamerica-east1'
      - '--memory'
      - '2Gi'
      - '--set-env-vars'
      - 'BUCKET_NOME=dados_alagoinhas_bronze,ROOT_PATH=financas,MUNICIPIO_IBGE=2900702,ANO_INICIO=2015,ANO_FIM=2027'
